"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 07:50:24.503130
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('artifact_key', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('can_use', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uses_remaining', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_grants'))
    )
    op.create_index('ix_admin_grants_target', 'admin_grants', ['target_user_id', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('admin_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('session_hash', sa.String(length=16), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_admin', 'audit_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_target', 'audit_logs', ['target_user_id', 'created_at'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backups')),
    sa.UniqueConstraint('filename', name=op.f('uq_backups_filename'))
    )
    op.create_table('biomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='natural', nullable=False),
    sa.Column('odds_per_sec', sa.Double(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), server_default='120', nullable=False),
    sa.Column('luck_mult', sa.Double(), server_default='1', nullable=False),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('item_boosts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('special_states', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('announce', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biomes')),
    sa.UniqueConstraint('key', name=op.f('uq_biomes_key'))
    )
    op.create_table('content_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_key', sa.String(length=128), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_overrides'))
    )
    op.create_index('ix_content_overrides_active', 'content_overrides', ['active', 'expires_at'], unique=False)
    op.create_table('discord_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_outbox'))
    )
    op.create_index('ix_discord_outbox_status', 'discord_outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('exc_type', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    op.create_index('ix_error_logs_created', 'error_logs', ['created_at'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_events')),
    sa.UniqueConstraint('key', name=op.f('uq_game_events_key'))
    )
    op.create_table('game_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_game_settings'))
    )
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_idempotency_keys'))
    )
    op.create_index('ix_idempotency_created', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('item_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_type', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Double(), server_default='1', nullable=False),
    sa.Column('value_mult', sa.Double(), server_default='1', nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_parts')),
    sa.UniqueConstraint('part_type', 'key', name='uq_item_parts_type_key')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('chain_key', sa.String(length=48), nullable=True),
    sa.Column('chain_step', sa.Integer(), nullable=True),
    sa.Column('objective', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('weight', sa.Double(), server_default='1', nullable=False),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests')),
    sa.UniqueConstraint('key', name=op.f('uq_quests_key'))
    )
    op.create_table('rarities',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('min_odds', sa.Double(), server_default='1', nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('color2', sa.String(length=16), nullable=False),
    sa.Column('luck_exponent', sa.Double(), server_default='1', nullable=False),
    sa.Column('xp', sa.Integer(), server_default='1', nullable=False),
    sa.Column('season_points', sa.Integer(), server_default='1', nullable=False),
    sa.Column('cutscene', sa.String(length=32), nullable=False),
    sa.Column('announce', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rarities')),
    sa.UniqueConstraint('key', name=op.f('uq_rarities_key'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('stardust_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('key', name=op.f('uq_recipes_key'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='scheduled', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('key', name=op.f('uq_seasons_key'))
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('biome_key', sa.String(length=48), nullable=True),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('key', name=op.f('uq_shops_key'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='player', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('status_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stardust', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('base_luck', sa.Double(), server_default='1.0', nullable=False),
    sa.Column('roll_counter', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('next_roll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_roll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_roll_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_roll_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_processed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title_key', sa.String(length=64), nullable=True),
    sa.Column('badge_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('profile_background', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stardust >= 0', name=op.f('ck_users_stardust_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('discord_id', name=op.f('uq_users_discord_id'))
    )
    op.create_index('ix_users_last_seen', 'users', ['last_seen_at'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), server_default='bronze', nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('first_achiever_id', sa.BigInteger(), nullable=True),
    sa.Column('first_achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('achiever_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['first_achiever_id'], ['users.id'], name=op.f('fk_achievements_first_achiever_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('key', name=op.f('uq_achievements_key'))
    )
    op.create_table('active_effects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('effect_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Double(), server_default='0', nullable=False),
    sa.Column('stack_mode', sa.String(length=16), server_default='add', nullable=False),
    sa.Column('remaining_rolls', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('biome_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_active_effects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_effects'))
    )
    op.create_index('ix_active_effects_expires', 'active_effects', ['expires_at'], unique=False)
    op.create_index('ix_active_effects_user', 'active_effects', ['user_id'], unique=False)
    op.create_table('artifact_cooldowns',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_key', sa.String(length=64), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uses', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artifact_cooldowns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'artifact_key', name=op.f('pk_artifact_cooldowns'))
    )
    op.create_table('boosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('effect_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Double(), server_default='0', nullable=False),
    sa.Column('rolls', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('stack_mode', sa.String(length=16), server_default='add', nullable=False),
    sa.Column('biome_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rarity_key', sa.String(length=32), nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sell_value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['rarity_key'], ['rarities.key'], name=op.f('fk_boosts_rarity_key_rarities'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boosts')),
    sa.UniqueConstraint('key', name=op.f('uq_boosts_key'))
    )
    op.create_table('cosmetics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('rarity_key', sa.String(length=32), nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['rarity_key'], ['rarities.key'], name=op.f('fk_cosmetics_rarity_key_rarities'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cosmetics')),
    sa.UniqueConstraint('key', name=op.f('uq_cosmetics_key'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('rarity_key', sa.String(length=32), nullable=False),
    sa.Column('luck_bonus', sa.Double(), server_default='0', nullable=False),
    sa.Column('speed_bonus', sa.Double(), server_default='0', nullable=False),
    sa.Column('passives', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sell_value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['rarity_key'], ['rarities.key'], name=op.f('fk_equipment_rarity_key_rarities'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('key', name=op.f('uq_equipment_key'))
    )
    op.create_table('gifts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('stardust', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_gifts_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_gifts_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gifts'))
    )
    op.create_index('ix_gifts_from', 'gifts', ['from_user_id', 'created_at'], unique=False)
    op.create_index('ix_gifts_to', 'gifts', ['to_user_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('lore', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=24), server_default='standard', nullable=False),
    sa.Column('rarity_key', sa.String(length=32), nullable=False),
    sa.Column('odds', sa.Double(), nullable=True),
    sa.Column('display_odds', sa.String(length=48), nullable=True),
    sa.Column('rollable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sell_value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('market_value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('biome_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('excluded_biome_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('min_luck', sa.Double(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('luck_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('animation', sa.String(length=32), nullable=True),
    sa.Column('sound', sa.String(length=32), nullable=True),
    sa.Column('tradeable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('procedural', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_discoverer_id', sa.BigInteger(), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fastest_user_id', sa.BigInteger(), nullable=True),
    sa.Column('fastest_roll_count', sa.BigInteger(), nullable=True),
    sa.Column('discovery_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('owner_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trade_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('serial_counter', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('odds IS NULL OR odds >= 1', name=op.f('ck_items_odds_min')),
    sa.ForeignKeyConstraint(['fastest_user_id'], ['users.id'], name=op.f('fk_items_fastest_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_discoverer_id'], ['users.id'], name=op.f('fk_items_first_discoverer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rarity_key'], ['rarities.key'], name=op.f('fk_items_rarity_key_rarities'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('key', name=op.f('uq_items_key'))
    )
    op.create_index('ix_items_kind', 'items', ['kind'], unique=False)
    op.create_index('ix_items_rarity', 'items', ['rarity_key'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('for_admins', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_admin', 'notifications', ['for_admins', 'created_at'], unique=False)
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('board', sa.String(length=32), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_rankings_season_id_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rankings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rankings'))
    )
    op.create_index('ix_rankings_board', 'rankings', ['board', 'season_id', 'rank'], unique=False)
    op.create_table('roll_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('roll_count', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rng_version', sa.SmallInteger(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('seen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_roll_batches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roll_batches'))
    )
    op.create_index('ix_roll_batches_user', 'roll_batches', ['user_id', 'id'], unique=False)
    op.create_table('rolls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('roll_number', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('biome_key', sa.String(length=48), nullable=False),
    sa.Column('biome_state', sa.String(length=48), nullable=True),
    sa.Column('luck', sa.Double(), nullable=False),
    sa.Column('base_odds', sa.Double(), nullable=False),
    sa.Column('final_chance', sa.Double(), nullable=False),
    sa.Column('equipment_mult', sa.Double(), server_default='1', nullable=False),
    sa.Column('boost_mult', sa.Double(), server_default='1', nullable=False),
    sa.Column('flags', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rng_version', sa.SmallInteger(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rolls_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rolls'))
    )
    op.create_index('ix_rolls_created', 'rolls', ['created_at'], unique=False)
    op.create_index('ix_rolls_item', 'rolls', ['item_id'], unique=False)
    op.create_index('ix_rolls_tier_created', 'rolls', ['tier', 'created_at'], unique=False)
    op.create_index('ix_rolls_user_id', 'rolls', ['user_id', 'id'], unique=False)
    op.create_table('season_stats',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rolls', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('points', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('best_odds', sa.Double(), server_default='0', nullable=False),
    sa.Column('first_discoveries', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_season_stats_season_id_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_season_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id', 'user_id', name=op.f('pk_season_stats'))
    )
    op.create_index('ix_season_stats_points', 'season_stats', ['season_id', 'points'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('admin_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('shop_key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('product_type', sa.String(length=16), nullable=False),
    sa.Column('product_key', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('limit_period', sa.String(length=16), nullable=True),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('requires_unlock', sa.String(length=64), nullable=True),
    sa.Column('biome_key', sa.String(length=48), nullable=True),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_shop_items_price_nonneg')),
    sa.ForeignKeyConstraint(['shop_key'], ['shops.key'], name=op.f('fk_shop_items_shop_key_shops'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_items')),
    sa.UniqueConstraint('key', name=op.f('uq_shop_items_key'))
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('offer_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('request_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('offer_stardust', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('request_stardust', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('offer_stardust >= 0 AND request_stardust >= 0', name=op.f('ck_trades_stardust_nonneg')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_trades_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_trades_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index('ix_trades_from', 'trades', ['from_user_id', 'status'], unique=False)
    op.create_index('ix_trades_to', 'trades', ['to_user_id', 'status'], unique=False)
    op.create_table('user_biomes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('biome_key', sa.String(length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_eval_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_biome_key', sa.String(length=48), nullable=True),
    sa.Column('state_key', sa.String(length=48), nullable=True),
    sa.Column('state_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_state_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_state_key', sa.String(length=48), nullable=True),
    sa.Column('forced', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('forced_by', sa.BigInteger(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_sig', sa.String(length=64), server_default='', nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_biomes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_biomes'))
    )
    op.create_index('ix_user_biomes_next', 'user_biomes', ['next_eval_at'], unique=False)
    op.create_table('user_cosmetics',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cosmetic_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='achievement', nullable=False),
    sa.Column('obtained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_cosmetics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'cosmetic_key', name=op.f('pk_user_cosmetics'))
    )
    op.create_table('user_quests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=32), nullable=False),
    sa.Column('objective', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('progress', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('target', sa.BigInteger(), nullable=False),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_user_quests_quest_id_quests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_quests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_quests')),
    sa.UniqueConstraint('user_id', 'quest_id', 'period_key', name='uq_user_quests_period')
    )
    op.create_index('ix_user_quests_user_status', 'user_quests', ['user_id', 'status'], unique=False)
    op.create_table('user_recipes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('crafted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_user_recipes_recipe_id_recipes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id', name=op.f('pk_user_recipes'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('user_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_rolls', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('offline_rolls', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('special_rolls', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('items_obtained', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('items_auto_deleted', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('best_odds', sa.Double(), server_default='0', nullable=False),
    sa.Column('best_item_id', sa.Integer(), nullable=True),
    sa.Column('discovered_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stardust_earned', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('items_sold', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('crafts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trades', sa.Integer(), server_default='0', nullable=False),
    sa.Column('market_sales', sa.Integer(), server_default='0', nullable=False),
    sa.Column('market_buys', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gifts_sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_discoveries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('boosts_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quests_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('achievements_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('artifacts_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_luck', sa.Double(), server_default='1', nullable=False),
    sa.Column('net_worth', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rarity_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('biomes_seen', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('counters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_stats'))
    )
    op.create_index('ix_user_stats_achievements', 'user_stats', ['achievements_count'], unique=False)
    op.create_index('ix_user_stats_best', 'user_stats', ['best_odds'], unique=False)
    op.create_index('ix_user_stats_discovered', 'user_stats', ['discovered_count'], unique=False)
    op.create_index('ix_user_stats_firsts', 'user_stats', ['first_discoveries'], unique=False)
    op.create_index('ix_user_stats_rolls', 'user_stats', ['total_rolls'], unique=False)
    op.create_index('ix_user_stats_worth', 'user_stats', ['net_worth'], unique=False)
    op.create_table('user_unlocks',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('unlock_key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_unlocks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unlock_key', name=op.f('pk_user_unlocks'))
    )
    op.create_table('world_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_world_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_events'))
    )
    op.create_index('ix_world_events_created', 'world_events', ['created_at'], unique=False)
    op.create_index('ix_world_events_type', 'world_events', ['type', 'created_at'], unique=False)
    op.create_table('admin_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ability', sa.Text(), server_default='', nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('target', sa.String(length=16), server_default='self', nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('cooldown_sec', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tier', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('player_usable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('equip_passive', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('transfer_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('audit_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_admin_artifacts_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_artifacts')),
    sa.UniqueConstraint('item_id', name=op.f('uq_admin_artifacts_item_id')),
    sa.UniqueConstraint('key', name=op.f('uq_admin_artifacts_key'))
    )
    op.create_table('collections',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('first_obtained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('times_obtained', sa.BigInteger(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_collections_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('pk_collections'))
    )
    op.create_index('ix_collections_item', 'collections', ['item_id'], unique=False)
    op.create_table('inventory',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('boost_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_qty_nonneg')),
    sa.ForeignKeyConstraint(['boost_id'], ['boosts.id'], name=op.f('fk_inventory_boost_id_boosts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'boost_id', name=op.f('pk_inventory'))
    )
    op.create_table('item_instances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('original_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('serial', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='owned', nullable=False),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('roll_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('obtained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_instances_item_id_items')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_item_instances_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_instances'))
    )
    op.create_index('ix_instances_owner_item', 'item_instances', ['owner_id', 'item_id'], unique=False)
    op.create_index('ix_instances_owner_obtained', 'item_instances', ['owner_id', 'obtained_at'], unique=False)
    op.create_table('item_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_revisions_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_revisions'))
    )
    op.create_index('ix_item_revisions_item', 'item_revisions', ['item_id', 'content_version'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('fee', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('flagged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price > 0', name=op.f('ck_market_listings_price_pos')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_market_listings_item_id_items')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_market_listings_seller_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_listings'))
    )
    op.create_index('ix_market_item_sold', 'market_listings', ['item_id', 'sold_at'], unique=False)
    op.create_index('ix_market_seller', 'market_listings', ['seller_id', 'status'], unique=False)
    op.create_index('ix_market_status_item', 'market_listings', ['status', 'item_id'], unique=False)
    op.create_index('uq_market_active_instance', 'market_listings', ['instance_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('shop_purchases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_total', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], name=op.f('fk_shop_purchases_shop_item_id_shop_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shop_purchases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_purchases'))
    )
    op.create_index('ix_shop_purchases_user_item', 'shop_purchases', ['user_id', 'shop_item_id', 'created_at'], unique=False)
    op.create_table('trade_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_items_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_items'))
    )
    op.create_index('ix_trade_items_instance', 'trade_items', ['instance_id'], unique=False)
    op.create_index('ix_trade_items_item', 'trade_items', ['item_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('world_first', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id', name=op.f('pk_user_achievements'))
    )
    op.create_table('user_equipment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Double(), server_default='1', nullable=False),
    sa.Column('quality_tier', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('luck_bonus', sa.Double(), server_default='0', nullable=False),
    sa.Column('speed_bonus', sa.Double(), server_default='0', nullable=False),
    sa.Column('equipped_slot', sa.String(length=16), nullable=True),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='craft', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('obtained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_user_equipment_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_equipment_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_equipment'))
    )
    op.create_index('ix_user_equipment_user', 'user_equipment', ['user_id'], unique=False)
    op.create_index('uq_user_equipment_slot', 'user_equipment', ['user_id', 'equipped_slot'], unique=True, postgresql_where=sa.text('equipped_slot IS NOT NULL'))
    op.create_table('user_item_prefs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_user_item_prefs_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_item_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('pk_user_item_prefs'))
    )
    op.create_table('showcases',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('slot >= 0 AND slot < 6', name=op.f('ck_showcases_slot_range')),
    sa.ForeignKeyConstraint(['instance_id'], ['item_instances.id'], name=op.f('fk_showcases_instance_id_item_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_showcases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'slot', name=op.f('pk_showcases'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showcases')
    op.drop_table('user_item_prefs')
    op.drop_index('uq_user_equipment_slot', table_name='user_equipment', postgresql_where=sa.text('equipped_slot IS NOT NULL'))
    op.drop_index('ix_user_equipment_user', table_name='user_equipment')
    op.drop_table('user_equipment')
    op.drop_table('user_achievements')
    op.drop_index('ix_trade_items_item', table_name='trade_items')
    op.drop_index('ix_trade_items_instance', table_name='trade_items')
    op.drop_table('trade_items')
    op.drop_index('ix_shop_purchases_user_item', table_name='shop_purchases')
    op.drop_table('shop_purchases')
    op.drop_index('uq_market_active_instance', table_name='market_listings', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_market_status_item', table_name='market_listings')
    op.drop_index('ix_market_seller', table_name='market_listings')
    op.drop_index('ix_market_item_sold', table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index('ix_item_revisions_item', table_name='item_revisions')
    op.drop_table('item_revisions')
    op.drop_index('ix_instances_owner_obtained', table_name='item_instances')
    op.drop_index('ix_instances_owner_item', table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_table('inventory')
    op.drop_index('ix_collections_item', table_name='collections')
    op.drop_table('collections')
    op.drop_table('admin_artifacts')
    op.drop_index('ix_world_events_type', table_name='world_events')
    op.drop_index('ix_world_events_created', table_name='world_events')
    op.drop_table('world_events')
    op.drop_table('user_unlocks')
    op.drop_index('ix_user_stats_worth', table_name='user_stats')
    op.drop_index('ix_user_stats_rolls', table_name='user_stats')
    op.drop_index('ix_user_stats_firsts', table_name='user_stats')
    op.drop_index('ix_user_stats_discovered', table_name='user_stats')
    op.drop_index('ix_user_stats_best', table_name='user_stats')
    op.drop_index('ix_user_stats_achievements', table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_table('user_settings')
    op.drop_table('user_recipes')
    op.drop_index('ix_user_quests_user_status', table_name='user_quests')
    op.drop_table('user_quests')
    op.drop_table('user_cosmetics')
    op.drop_index('ix_user_biomes_next', table_name='user_biomes')
    op.drop_table('user_biomes')
    op.drop_index('ix_trades_to', table_name='trades')
    op.drop_index('ix_trades_from', table_name='trades')
    op.drop_table('trades')
    op.drop_table('shop_items')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_season_stats_points', table_name='season_stats')
    op.drop_table('season_stats')
    op.drop_index('ix_rolls_user_id', table_name='rolls')
    op.drop_index('ix_rolls_tier_created', table_name='rolls')
    op.drop_index('ix_rolls_item', table_name='rolls')
    op.drop_index('ix_rolls_created', table_name='rolls')
    op.drop_table('rolls')
    op.drop_index('ix_roll_batches_user', table_name='roll_batches')
    op.drop_table('roll_batches')
    op.drop_index('ix_rankings_board', table_name='rankings')
    op.drop_table('rankings')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_index('ix_notifications_admin', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_items_rarity', table_name='items')
    op.drop_index('ix_items_kind', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_gifts_to', table_name='gifts')
    op.drop_index('ix_gifts_from', table_name='gifts')
    op.drop_table('gifts')
    op.drop_table('equipment')
    op.drop_table('cosmetics')
    op.drop_table('boosts')
    op.drop_table('artifact_cooldowns')
    op.drop_index('ix_active_effects_user', table_name='active_effects')
    op.drop_index('ix_active_effects_expires', table_name='active_effects')
    op.drop_table('active_effects')
    op.drop_table('achievements')
    op.drop_index('ix_users_last_seen', table_name='users')
    op.drop_table('users')
    op.drop_table('shops')
    op.drop_table('seasons')
    op.drop_table('recipes')
    op.drop_table('rarities')
    op.drop_table('quests')
    op.drop_table('item_parts')
    op.drop_index('ix_idempotency_created', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('game_settings')
    op.drop_table('game_events')
    op.drop_index('ix_error_logs_created', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('ix_discord_outbox_status', table_name='discord_outbox')
    op.drop_table('discord_outbox')
    op.drop_index('ix_content_overrides_active', table_name='content_overrides')
    op.drop_table('content_overrides')
    op.drop_table('biomes')
    op.drop_table('backups')
    op.drop_index('ix_audit_target', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_admin', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_admin_grants_target', table_name='admin_grants')
    op.drop_table('admin_grants')
    # ### end Alembic commands ###
