"""Japanese display names for seeded content.

Descriptions were written in Japanese from the start; only the names were not.
They live here rather than inline in the seed dicts so the whole vocabulary can
be read and revised in one place, and so a name can be corrected without
touching the balance data next to it.

The English name stays primary — it carries the setting — and this is shown
beside it. Content created later from the admin panel has its own editable
``name_ja`` field and does not need an entry here.
"""
from __future__ import annotations

RARITIES = {
    "common": "並",
    "rare": "稀少",
    "epic": "英雄級",
    "legendary": "伝説級",
    "secret": "秘匿級",
    "ultra_secret": "超秘匿級",
    "mythic": "神話級",
    "admin": "管理者遺物",
}

ITEMS = {
    # --- common -----------------------------------------------------------
    "cosmic_dust": "宇宙塵",
    "stardust_mote": "星屑のかけら",
    "space_pebble": "宇宙の小石",
    "ion_spark": "イオンの火花",
    "frozen_vapor": "凍てついた蒸気",
    "lunar_sand": "月の砂",
    "orbit_fragment": "軌道の破片",
    "nebula_wisp": "星雲のたなびき",
    "photon_bead": "光子の粒",
    "quartz_meteorite": "石英隕石",
    "solar_ember": "太陽の残り火",
    "comet_tail": "彗星の尾",
    "meteor_chunk": "隕石塊",
    "void_pebble": "虚無の小石",
    "bloom_petal": "開花する花弁",
    "qubit_bubble": "量子ビットの泡",
    "comet_ice": "彗星の氷",
    "flare_cinder": "フレアの燃え殻",
    # --- rare -------------------------------------------------------------
    "gravity_pearl": "重力の真珠",
    "aurora_thread": "極光の糸",
    "starlit_feather": "星明かりの羽根",
    "plasma_orb": "プラズマ球",
    "celestial_prism": "天のプリズム",
    "moonstone_heart": "月長石の心臓",
    "ringed_crystal": "環状結晶",
    "impact_crystal": "衝突結晶",
    "aurora_silk": "極光の絹",
    "nebula_rose": "星雲の薔薇",
    "glacial_heart": "氷河の心臓",
    "entangled_pair": "もつれ合う対",
    "fallen_star": "堕ちた星",
    "void_shard": "虚無の欠片",
    "burning_iron_shard": "灼熱の鉄片",
    # --- epic ---------------------------------------------------------------
    "pulsar_core": "パルサーの核",
    "cosmic_lotus": "宇宙蓮",
    "quasar_shard": "クェーサーの破片",
    "starforged_key": "星鍛えの鍵",
    "eclipse_ring": "食の環",
    "magnetar_eye": "マグネターの瞳",
    "chrono_sand": "時の砂",
    "galactic_compass": "銀河羅針盤",
    "weekend_nebula": "週末の星雲",
    "shooting_star_core": "流星の核",
    "borealis_lantern": "極光の灯",
    "pink_quasar": "桃色クェーサー",
    "blood_moon_shard": "血月の欠片",
    "compressed_star": "圧縮された星",
    "rift_walker_mask": "裂け目を渡る者の仮面",
    "wishing_star": "願いの星",
    "schrodingers_box": "シュレーディンガーの箱",
    "frozen_second": "凍結した一秒",
    # --- legendary ----------------------------------------------------------
    "supernova_remnant": "超新星残骸",
    "dark_matter_cube": "暗黒物質の立方体",
    "event_horizon_tear": "事象の地平の裂け目",
    "astral_crown": "星辰の王冠",
    "resonance_shard": "共鳴する欠片",
    "binary_star_pendant": "連星のペンダント",
    "midnight_comet": "真夜中の彗星",
    "wormhole_gate": "虫食い穴の門",
    "cosmic_phoenix_feather": "宇宙不死鳥の羽根",
    "stellar_nursery": "星のゆりかご",
    "nova_sigil": "新星の印",
    "corona_crown": "コロナの冠",
    "veil_of_lights": "光のヴェール",
    "absolute_frost": "絶対零度の霜",
    "crimson_halo": "深紅の光輪",
    "null_heart": "空虚の心臓",
    "spaghettified_light": "引き伸ばされた光",
    "forged_relic": "鍛えられし遺物",
    "paradox_shard": "逆説の欠片",
    # --- secret -------------------------------------------------------------
    "zenith_hourglass": "天頂の砂時計",
    "galaxy_in_a_bottle": "瓶詰めの銀河",
    "leviathan_scale": "天空鯨の鱗",
    "starborn_halo": "星生まれの光輪",
    "chronos_gear": "クロノスの歯車",
    "fortunes_edge": "幸運の刃",
    "andromeda_tear": "アンドロメダの涙",
    "quasar_heart": "クェーサーの心臓",
    "dyson_fragment": "ダイソン球の破片",
    "lucky_seven_relic": "幸運の七の遺物",
    "heart_of_the_sun": "太陽の心臓",
    "red_giants_tear": "赤色巨星の涙",
    "abyssal_eye": "深淵の瞳",
    "hawking_radiance": "ホーキング輝",
    "star_sovereign": "星の君主",
    "genesis_spark": "創生の火花",
    "golden_ratio": "黄金比",
    "stellar_artifact": "恒星の遺物",
    # --- ultra secret -------------------------------------------------------
    "primordial_star": "原初の星",
    "the_last_light": "最後の光",
    "crown_of_the_cosmos": "宇宙の王冠",
    "multiverse_key": "多元宇宙の鍵",
    "luck_incarnate": "幸運の化身",
    "event_horizon_crown": "事象の地平の冠",
    "first_word": "最初の言葉",
    "creators_fingerprint": "創造主の指紋",
    "architects_blueprint": "設計者の青写真",
    "sanctum_relic": "聖域の遺物",
    "shattered_mirror": "砕けた鏡",
    "source_code_fragment": "原初コードの断片",
    "laurel_of_firsts": "初踏の月桂冠",
    "pioneer_starmedal": "開拓者の星章",
    "everbloom": "永遠に咲くもの",
    # --- mythic -------------------------------------------------------------
    "big_bang_echo": "ビッグバンの残響",
    "infinity_ouroboros": "無限のウロボロス",
    "eye_of_the_universe": "宇宙の瞳",
    "god_particle": "神の粒子",
    "the_origin": "始まりのもの",
    "genesis_codex": "創世の典",
    "heavens_gate": "天の門",
    "omega": "オメガ",
    # --- admin artifacts ----------------------------------------------------
    "aa_infinite_luck": "無限の幸運",
    "aa_time_breaker": "時の破壊者",
    "aa_void_key": "虚無の鍵",
    "aa_reality_shift": "現実改変",
    "aa_star_forger": "星を鍛えし者",
    "aa_system_override": "系統上書き",
    "aa_cosmic_eye": "宇宙の眼",
    "aa_world_fracture": "世界断裂",
    "aa_chrono_loop": "時間循環",
    "aa_entropy_crown": "熱的死の冠",
    "aa_genesis_seed": "創世の種",
    "aa_singularity_engine": "特異点機関",
    "aa_oracle_lens": "神託の鏡",
    "aa_aether_tap": "霊気の導管",
    "aa_biome_conductor": "Biome指揮者",
    "aa_probability_anchor": "確率の錨",
    "aa_luck_singularity": "幸運の特異点",
    "aa_event_horizon": "事象の地平",
    "aa_starfall_call": "星降りの号令",
    "aa_null_codex": "空白の典",
    "aa_mirror_of_echoes": "反響の鏡",
    "aa_divine_decree": "神の勅令",
    "aa_astral_compass": "星辰の羅針盤",
    "aa_quantum_dice": "量子の賽",
    "aa_celestial_anvil": "天の金床",
    "aa_eternity_glass": "永劫のガラス",
    "aa_halo_of_first_light": "最初の光の光輪",
    "aa_omega_protocol": "オメガ規約",
    "aa_phantom_thread": "幻影の糸",
    "aa_architects_sigil": "設計者の紋章",
    "aa_gravity_well": "重力の井戸",
    "aa_temporal_key": "時間の鍵",
    "gen:forged_relic:burning-iron-shard": "灼熱の鉄片",
}

BIOMES = {
    "stellar_drift": "恒星の漂流",
    "nebula_bloom": "星雲の開花",
    "solar_flare": "太陽フレア",
    "meteor_storm": "流星嵐",
    "aurora_veil": "極光のヴェール",
    "frozen_comet": "凍てつく彗星",
    "crimson_eclipse": "深紅の食",
    "quantum_foam": "量子の泡",
    "starfall": "星降り",
    "void_rift": "虚無の裂け目",
    "singularity": "特異点",
    "genesis": "創世",
    "chrono_vault": "時律の宝物庫",
    "architects_domain": "設計者の領域",
    "void_sanctum": "虚無の聖域",
    "fractured_reality": "砕けた現実",
    "the_source": "根源",
}

EQUIPMENT = {
    "stargazer_glove": "観星の手甲",
    "comet_gauntlet": "彗星の籠手",
    "nebula_grasp": "星雲を掴む手",
    "solar_fist": "太陽の拳",
    "gravity_gauntlet": "重力の籠手",
    "eclipse_hand": "食の手",
    "hand_of_the_cosmos": "宇宙の手",
    "genesis_gauntlet": "創世の籠手",
    "ion_core": "イオン炉心",
    "plasma_core": "プラズマ炉心",
    "pulsar_engine": "パルサー機関",
    "quasar_reactor": "クェーサー炉",
    "chrono_engine": "時律機関",
    "singularity_drive": "特異点駆動機",
    "lucky_star_charm": "幸運星のお守り",
    "biome_compass": "Biome羅針盤",
    "auto_sifter": "自動選別器",
    "moonlit_amulet": "月光の護符",
    "fortune_idol": "幸運の偶像",
    "eye_of_providence": "摂理の眼",
    "meteor_knuckle": "流星の拳",
    "frostbite_grip": "凍傷の握り",
    "aurora_palm": "極光の掌",
    "drift_core": "漂流炉心",
    "storm_dynamo": "嵐の発電機",
    "starfall_turbine": "星降りの羽根",
    "collectors_lens": "蒐集家のレンズ",
    "echo_locket": "反響のロケット",
    "prism_sigil": "稜鏡の紋章",
    "paradox_clock": "逆説の時計",
}

BOOSTS = {
    "starlight_candle": "星明かりの蝋燭",
    "stellar_tonic": "恒星の強壮薬",
    "fortune_elixir": "幸運の霊薬",
    "next_roll_boost": "次回抽選強化",
    "triple_charm": "三重のお守り",
    "cosmic_stock": "宇宙の備蓄",
    "celestial_surge": "天体の高まり",
    "rare_guarantee": "稀少確定",
    "epic_guarantee": "英雄確定",
    "special_amplifier": "特別抽選増幅器",
    "overdrive_chip": "過駆動チップ",
    "chrono_capsule": "時律カプセル",
    "biome_magnet": "Biome磁石",
    "nebula_incense": "星雲の香",
    "solar_lens": "太陽レンズ",
    "void_resonator": "虚無共鳴器",
}

COSMETICS = {
    # --- titles -------------------------------------------------------------
    "t_newcomer": "新参者",
    "t_stargazer": "観星者",
    "t_voyager": "航海者",
    "t_pathfinder": "先導者",
    "t_collector": "蒐集家",
    "t_curator": "宇宙の管理人",
    "t_legend_seeker": "伝説を追う者",
    "t_secret_keeper": "秘密の守り手",
    "t_beyond_reason": "理を超えて",
    "t_unknown": "???",
    "t_pioneer": "開拓者",
    "t_world_first": "世界初",
    "t_merchant": "星の商人",
    "t_tycoon": "銀河の大富豪",
    "t_artisan": "職人",
    "t_luck_incarnate": "幸運の化身",
    "t_void_walker": "虚無を歩む者",
    "t_wanderer": "宇宙の放浪者",
    "t_devoted": "傾倒せし者",
    "t_eternal": "永劫の回し手",
    "t_lucky_seven": "幸運の七",
    "t_blessed": "設計者の祝福",
    "t_questor": "依頼人",
    "t_benefactor": "施しの人",
    "t_night_owl": "夜更かし",
    # --- badges -------------------------------------------------------------
    "b_first_roll": "初回の抽選",
    "b_rare": "稀少狩り",
    "b_epic": "英雄狩り",
    "b_legendary": "伝説狩り",
    "b_secret": "秘匿狩り",
    "b_ultra": "超秘匿狩り",
    "b_mythic": "???",
    "b_pioneer": "開拓者",
    "b_world_first": "世界初",
    "b_roller_10k": "1万回の回し手",
    "b_roller_1m": "100万回の回し手",
    "b_biome_master": "Biomeの達人",
    "b_void": "虚無に触れし者",
    "b_trader": "交易者",
    "b_artisan": "職人",
    "b_luck": "幸運100万",
    "b_admin_blessing": "設計者の刻印",
    # --- backgrounds ---------------------------------------------------------
    "bg_default": "深宇宙",
    "bg_nebula": "星雲の開花",
    "bg_solar": "太陽フレア",
    "bg_aurora": "極光のヴェール",
    "bg_frost": "凍てつく彗星",
    "bg_eclipse": "深紅の食",
    "bg_starfall": "星降り",
    "bg_void": "虚無の裂け目",
    "bg_singularity": "特異点",
    "bg_genesis": "創世",
    "bg_golden": "黄金の書庫",
    # --- season pass ---------------------------------------------------------
    "t_season_runner": "季を駆ける者",
    "t_season_sovereign": "季の覇者",
    "b_season_ace": "季の名手",
    "bg_season_meteor": "流星の季",
    # --- prestige ------------------------------------------------------------
    "t_reborn_1": "再誕者",
    "t_reborn_3": "三度の再誕者",
    "t_reborn_5": "永劫回帰",
    "t_reborn_10": "輪を断つ者",
    # --- collection sets -----------------------------------------------------
    "t_set_master": "図鑑の織り手",
    # --- cosmic atelier ------------------------------------------------------
    "t_atelier_patron": "工房の常連",
    "t_starlit": "星明かりを纏う者",
    "t_quiet_orbit": "静かな軌道",
    "t_lantern_bearer": "灯りを持つ者",
    "b_atelier_seal": "工房の印",
    "b_comet_tail": "彗星の尾",
    "b_paper_moon": "紙の月",
    "b_orbit_ring": "軌道環",
    "bg_quiet_dust": "静かな塵",
    "bg_amber_drift": "琥珀の漂い",
    "bg_glass_sea": "硝子の海",
}

SHOPS = {
    "stellar_exchange": "恒星交易所",
    "filter_lab": "選別研究所",
    "nebula_bazaar": "星雲market",
    "solar_forge": "太陽鍛冶場",
    "void_market": "虚無の市",
    "cosmic_atelier": "宇宙の仕立て工房",
}

RECIPES = {
    "r_stargazer_glove": "観星の手甲の作製",
    "r_ion_core": "イオン炉心の錬成",
    "r_comet_gauntlet": "彗星の籠手の作製",
    "r_plasma_core": "プラズマ炉心の錬成",
    "r_lucky_star_charm": "幸運星のお守りの作製",
    "r_nebula_grasp": "星雲を掴む手の作製",
    "r_solar_fist": "太陽の拳の鍛造",
    "r_pulsar_engine": "パルサー機関の組成",
    "r_auto_sifter": "自動選別器の組立",
    "r_biome_compass": "Biome羅針盤の作製",
    "r_moonlit_amulet": "月光の護符の作製",
    "r_gravity_gauntlet": "重力の籠手の鍛造",
    "r_eclipse_hand": "食の手の鍛造",
    "r_quasar_reactor": "クェーサー炉の組成",
    "r_fortune_idol": "幸運の偶像の彫成",
    "r_chrono_engine": "時律機関の組成",
    "r_eye_of_providence": "摂理の眼の開眼",
    "r_hand_of_the_cosmos": "宇宙の手の鍛造",
    "r_singularity_drive": "特異点駆動機の組成",
    "r_genesis_gauntlet": "創世の籠手の鍛造",
    "r_next_roll_boost": "次回抽選強化の調合",
    "r_rare_guarantee": "稀少確定の調合",
    "r_fortune_elixir": "幸運の霊薬の調合",
    "r_cosmic_gamble": "宇宙の賭けの調合",
    "r_stellar_fusion": "恒星融合",
    "r_everbloom": "永遠に咲くものの育成",
    "r_paradox_clock": "逆説の時計の組立",
    "r_prism_cascade": "プリズム連鎖の調律",
}

ACHIEVEMENTS = {
    "rolls_1": "はじめての抽選",
    "rolls_10": "抽選 10回",
    "rolls_100": "抽選 100回",
    "rolls_1000": "抽選 1,000回",
    "rolls_5000": "抽選 5,000回",
    "rolls_10000": "抽選 10,000回",
    "rolls_50000": "抽選 50,000回",
    "rolls_100000": "抽選 100,000回",
    "rolls_500000": "抽選 500,000回",
    "first_mythic": "???",
    "legendary_10": "伝説級 ×10",
    "legendary_50": "伝説級 ×50",
    "secret_5": "秘匿級 ×5",
    "epic_100": "英雄級 ×100",
    "collect_10": "蒐集 10種",
    "collect_25": "蒐集 25種",
    "collect_50": "蒐集 50種",
    "collect_75": "蒐集 75種",
    "collect_100": "蒐集 100種",
    "biome_nebula_bloom": "星雲の開花を見た",
    "biome_solar_flare": "太陽フレアを見た",
    "biome_meteor_storm": "流星嵐を見た",
    "biome_aurora_veil": "極光のヴェールを見た",
    "biome_frozen_comet": "凍てつく彗星を見た",
    "biome_crimson_eclipse": "深紅の食を見た",
    "biome_quantum_foam": "量子の泡を見た",
    "biome_starfall": "星降りを見た",
    "biome_void_rift": "虚無の裂け目を見た",
    "biomes_5": "Biome踏破者",
    "biomes_all": "Biomeの達人",
    "earn_10000": "10,000スターダスト獲得",
    "earn_100000": "100,000スターダスト獲得",
    "earn_1000000": "1,000,000スターダスト獲得",
    "earn_10000000": "10,000,000スターダスト獲得",
    "earn_100000000": "100,000,000スターダスト獲得",
    "sell_100": "売却 100回",
    "sell_1000": "売却 1,000回",
    "sell_10000": "売却 10,000回",
    "craft_10": "調合 10回",
    "craft_50": "調合 50回",
    "craft_200": "調合 200回",
    "luck_10": "幸運 10倍",
    "luck_10000": "幸運 10,000倍",
    "luck_100000": "幸運 100,000倍",
    "luck_1000000": "幸運 1,000,000倍",
    "firsts_1": "世界初発見者",
    "firsts_5": "世界初発見 5回",
    "firsts_25": "世界初発見 25回",
    "lucky_seven": "幸運の七",
    "omega": "終わりに至る",
    "resonance": "共鳴の兆し",
    "midnight": "真夜中の監視者",
    "architect_blessing": "設計者の祝福",
    "everbloom": "永遠の庭",
    "rolls_1000000": "抽選 1,000,000回",
    "level_5": "レベル5",
    "level_10": "レベル10",
    "level_25": "レベル25",
    "level_50": "レベル50",
    "level_100": "レベル100",
    "biome_singularity": "特異点に至った",
    "biome_genesis": "創世を見た",
    "craft_1": "はじめての調合",
    "luck_100": "幸運 100倍",
    "luck_1000": "幸運 1,000倍",
    "dust_lover": "塵は塵に",
}

QUESTS = {
    "h_eleven": "11:11",
}

# Table name -> {content key: Japanese name}
# Shop listings. A listing usually resells a boost, so it borrows that boost's
# wording; the upgrade licences are the shop's own goods and are named here.
SHOP_ITEMS = {
    "s_biome_magnet": "Biome磁石",
    "s_celestial_surge": "天体の高まり",
    "s_chrono_capsule": "時律カプセル",
    "s_cosmic_stock": "宇宙の備蓄",
    "s_epic_guarantee": "英雄確定",
    "s_fortune_elixir": "幸運の霊薬",
    "s_ion_core": "イオン核",
    "s_nebula_incense": "星雲の香",
    "s_nebula_tonic": "恒星の強壮薬（特価）",
    "s_next_roll_boost": "次回抽選強化",
    "s_overdrive_chip": "過駆動チップ",
    "s_rare_guarantee": "稀少確定",
    "s_solar_chip": "過駆動チップ（特価）",
    "s_solar_lens": "太陽レンズ",
    "s_special_amplifier": "特別抽選増幅器",
    "s_stargazer_glove": "観星者の手袋",
    "s_starlight_candle": "星明かりの蝋燭",
    "s_stellar_tonic": "恒星の強壮薬",
    "s_triple_charm": "三重のお守り",
    "s_void_resonator": "虚無共鳴器",
    "u_auto_skip_100": "自動スキップ 1/100",
    "u_auto_skip_1000": "自動スキップ 1/1,000",
    "u_auto_skip_10000": "自動スキップ 1/10,000",
    "u_auto_skip_custom": "カスタムフィルター許可証",
    "u_fast_mode": "高速モジュール",
    "u_inventory_exp": "所持枠の拡張",
    "u_offline_1": "オフライン処理装置I",
    "u_offline_2": "オフライン処理装置II",
    "u_rng_analyzer": "確率解析器",
    "c_atelier_patron": "称号: 工房の常連",
    "c_quiet_orbit": "称号: 静かな軌道",
    "c_starlit": "称号: 星明かりを纏う者",
    "c_lantern_bearer": "称号: 灯りを持つ者",
    "c_atelier_seal": "バッジ: 工房の印",
    "c_paper_moon": "バッジ: 紙の月",
    "c_comet_tail": "バッジ: 彗星の尾",
    "c_orbit_ring": "バッジ: 軌道環",
    "c_bg_quiet_dust": "背景: 静かな塵",
    "c_bg_amber_drift": "背景: 琥珀の漂い",
    "c_bg_glass_sea": "背景: 硝子の海",
    "u_ultra_fast": "超高速モジュール",
}

SEASONS = {
    "season_1": "シーズン1: 最初の光",
}

# Parts of procedurally generated items. A generated item's Japanese name is
# these four words in Japanese order (modifier, effect, material, shape), so
# "Radiant Gold Orb of Dawn" reads "暁の輝く黄金の宝珠".
ITEM_PARTS = {
    # materials（〜の）
    "iron": "鉄の", "copper": "銅の", "silver": "銀の", "gold": "黄金の", "obsidian": "黒曜石の",
    "moonsilver": "月銀の", "starsteel": "星鋼の", "nebulite": "星雲石の", "orichalcum": "オリハルコンの",
    "voidglass": "虚無硝子の", "aetherium": "エーテリウムの", "neutronium": "中性子石の",
    # shapes
    "ring": "指輪", "shard": "破片", "orb": "宝珠", "idol": "神像", "prism": "稜鏡", "chalice": "聖杯",
    "sigil": "印章", "crown": "王冠", "mask": "仮面", "astrolabe": "星盤",
    # effects（連体形）
    "glowing": "輝く", "humming": "唸る", "shimmering": "煌めく", "radiant": "光り輝く", "resonant": "共鳴する",
    "frozen": "凍てつく", "burning": "燃える", "cursed": "呪われた", "blessed": "祝福された", "eternal": "永遠の",
    "paradoxical": "逆説の",
    # modifiers（〜の）
    "dawn": "暁の", "silence": "静寂の", "void": "虚無の", "andromeda": "アンドロメダの",
    "suns": "万の太陽の", "first_star": "最初の星の", "infinity": "無限の",
}

BY_TABLE: dict[str, dict[str, str]] = {
    "rarities": RARITIES,
    "items": ITEMS,
    "biomes": BIOMES,
    "equipment": EQUIPMENT,
    "boosts": BOOSTS,
    "cosmetics": COSMETICS,
    "shops": SHOPS,
    "recipes": RECIPES,
    "achievements": ACHIEVEMENTS,
    "quests": QUESTS,
    "shop_items": SHOP_ITEMS,
    "seasons": SEASONS,
    "item_parts": ITEM_PARTS,
}
